spring:
  datasource:
    url: jdbc:mysql://localhost:3306/managementTournoiFootYc?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        globally_quoted_identifiers: true
        hbm2ddl:
          auto: create