spring:
  datasource:
    url: jdbc:mysql://localhost:3306/managementTournoiFootYc1?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        globally_quoted_identifiers: true
        hbm2ddl:
          auto: create
  servlet:
    multipart:
      enabled: true
  # Threshold after which files are written to disk.
      file-size-threshold: 2KB
  # Max file size.
      max-file-size: 20MB
  # Max Request Size
    multipart.max-request-size: 20MB
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: youcodesoccer@gmail.com
    password: wpaz mvzn bnwg ccro
    port: 587
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 9000
socceryc:
  seedFakeData: true
cloudinary:
  cloud_name: dncljj3e2
  api_key: 347914715559372
  api_secret: _rzJHdnfsCuSUG7--vdzLfkAHFo